### ISSUE TITLE
Починить сборку в master:

### ISSUE THREAD

**Issue by pashakhorikov** [shchegol/reactive-battle#12]
При попытке выполнить сборку проекта возникают следующие ошибки: 

- [x] npm install без warning'ов
- [x] Unknown plugin: imagemin-gifsicle
- [x] Unknown plugin: imagemin-jpegtran
- [x] Unknown plugin: imagemin-optipng
- [x] Unknown plugin: imagemin-svgo

Нужно либо добавить недостающие плагины в зависимости или совсем исключить из проекта, если они не используются.

**Comment by shchegol** [comment]
@pashakhorikov Уточнение про какие именно ворнинги индёт речь? Про эти:
```
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```
или про эти?
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```
Я просто начал сейчас разбираться в проблеме и понял что большинство этих ворнингов ведут к таким пакетам как jest, webpack-dev-server и тп. Как с этим жить?

**Comment by pashakhorikov** [comment]
> @pashakhorikov Уточнение про какие именно ворнинги индёт речь? Про эти:
> 
> ```
> npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
> npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
> npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
> npm WARN deprecated request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
> npm WARN deprecated har-validator@5.1.5: this library is no longer supported
> ```
> 
> или про эти?
> 
> ```
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\webpack-dev-server\node_modules\chokidar\node_modules\fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
> ```
> 
> Я просто начал сейчас разбираться в проблеме и понял что большинство этих ворнингов ведут к таким пакетам как jest, webpack-dev-server и тп. Как с этим жить?

В данном случае пока достаточно обеспечить все необходимые плагины, которые есть в проекте, либо исключить их совсем, если они не используются. Я про это 
 Unknown plugin: imagemin-gifsicle
 Unknown plugin: imagemin-jpegtran
 Unknown plugin: imagemin-optipng
 Unknown plugin: imagemin-svgo

Остальные warnings пока можно не обращать внимание. Мы к ним позже вернемся, когда будем готовить сборку к релизу.
