### ISSUE TITLE
Проверить проект на утечки памяти.

### ISSUE THREAD

**Issue by pashakhorikov** [shchegol/reactive-battle#38]

**Comment by zemer** [comment]
1. Проверка утеки после загрузки страницы и ввода неверных данных несколько раз. Сборщик мусора собрал всё (и даже больше). **Утечек нет.**
![image](https://user-images.githubusercontent.com/897766/106716833-f66fd980-660f-11eb-9a3f-2c71a530a291.png)

2. Проверка успешного входа и выхода пользователя несколько раз. Есть **незначительная утечка** памяти (218 492). На старте 10768996. После конечной сборки 10987488.
![2021-02-03 11_27_10-Window](https://user-images.githubusercontent.com/897766/106719272-29679c80-6613-11eb-97f8-c63e4f994b19.png)

3. Проверка регистрации и выхода обратно на страницу входа. На входе 11217688, на выходе 11167992 (-49 696). **Утечек нет.**
![image](https://user-images.githubusercontent.com/897766/106720491-992a5700-6614-11eb-8281-bd82e80821f2.png)

4. Вход на страницу редактирования профиля, редактирования профиля, смена аватара и выход на страницу профиля. На входе 11495316, после очистки 10640520 (-854 796). **Утечек нет.**
![image](https://user-images.githubusercontent.com/897766/106721178-6765c000-6615-11eb-901e-5c9848422ba4.png)

5. Вход на страницу форума, добавление нескольких сообщений, выход к списку форумов. На входе 10006360, после сборки 9651804 (-354 556). **Утечек нет.**
![image](https://user-images.githubusercontent.com/897766/106722373-ef989500-6616-11eb-9496-2d4dffd32bbe.png)

6. Процесс игры, движения танка, выстрелы. На старте 10383140, после последней сборки 10227268 (-155 872). **Утечек нет.**
![image](https://user-images.githubusercontent.com/897766/106722924-97ae5e00-6617-11eb-804c-a255936b8bee.png)

**Вывод: критичных утечек в приложении нет.**
